/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as knftCollectionSingleSol from "./KNFTCollection_Single.sol";
export { KNFTCollection__factory } from "./KNFTCollection__factory";
export { NFTCollectible__factory } from "./NFTCollectible__factory";
