/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as knftCollectionSingleSol from "./KNFTCollection_Single.sol";
export type { knftCollectionSingleSol };
export type { KNFTCollection } from "./KNFTCollection";
export type { NFTCollectible } from "./NFTCollectible";
